- src/components/strategies/create/CreateStrategyOrders.tsx
> #685 - Create Strategy Disclaimer

- src/components/tradingviewChart/widget.tsx
> allowing symbol change in trade chart

- src/components/trade/orderWidget/useOrderBookWidget.ts
> set min amount threshold for orderbook row

- src/App.tsx
- src/components/core/menu/mobileMenu/MobileMenu.tsx
- src/components/strategies/create/CreateStrategyCTA.tsx
> #713 - Create Strategy CTA

- public/locales/en-US/translation.en-US.json
- public/locales/xx-XX/translation.xx-XX.json
- src/components/core/menu/mainMenu/MainMenuRightBurger/useBurgerMenuItems.tsx
- src/libs/routing/routes.tsx
- src/libs/translations/version.ts
> 730 dune link

- src/components/core/menu/mainMenu/MainMenuRightBurger/useMenuContext.tsx
Check mark near currency was not updating whene the currency was being changed. My solution is closing whole menu on currency change.
> sub menu problem fix

- src/components/common/TokenInputField/TokenInputField.tsx
- src/components/common/approval/ApproveToken.tsx
- src/components/common/imager/Imager.tsx
- src/components/common/selectToken/index.tsx
- src/components/common/selectTokens/index.tsx
- src/components/common/tokensOverlap/index.tsx
- src/components/strategies/create/BuySellBlock/index.tsx
- src/components/strategies/edit/EditStrategyAllocatedBudget.tsx
- src/components/strategies/overview/strategyBlock/StrategyBlockBuySell.tsx
- src/components/strategies/overview/strategyBlock/TokenPrice.tsx
- src/components/strategies/portfolio/allTokens/PortfolioAllTokensDesktop.tsx
- src/components/strategies/portfolio/allTokens/PortfolioAllTokensMobile.tsx
- src/components/strategies/portfolio/token/PortfolioTokenHeader.tsx
- src/components/strategies/portfolio/token/PortfolioTokenPieChartCenter.tsx
- src/libs/modals/modals/ModalTokenList/ModalTokenListContent.tsx
- src/libs/modals/modals/ModalTradeRouting/ModalTradeRoutingRowCell.tsx
> 669 round logos

- src/components/trade/settings/TradeSettings.tsx
> Move unit to description

- src/libs/modals/ModalProvider.tsx
> Check scroll target present before disabling scroll

- src/components/simulator/mobile-placeholder.tsx
- src/components/simulator/result/SimResultChartDownload.tsx
- src/pages/simulator/index.tsx
> [Simulator] placeholder & tooltip

- index.html
fix #1063 
Add social tag in index.html
> Add social tags

- src/components/simulator/input/SimInputStrategyType.tsx
- src/components/simulator/input/SimInputTokenSelection.tsx
- src/components/simulator/result/SimResultSummaryGains.tsx
- src/components/simulator/result/SimResultSummaryRoi.tsx
Simulator input page
- Add token selection tooltip
- Add strategy type tooltips
Simulator result page
- Remove TBD from ROI tooltip
- Add Estimated Gains tooltip
> Add simulator tooltips

- src/components/simulator/result/SimResultSummary.tsx
SimResultSummary was accessing properties of state.baseToken and state.quoteToken before loading finished and isLoading was set to false
Fixes #1082
> Fix SimResultSummary accessing undefined properties

- src/components/common/datePicker/DateRangePicker.tsx
- src/components/common/selectToken/index.tsx
- src/components/simulator/input/SimInputChart.tsx
- src/components/simulator/input/SimInputOverlapping.tsx
- src/components/simulator/input/SimInputRecurring.tsx
- src/components/simulator/input/SimInputTokenSelection.tsx
- src/components/simulator/input/d3Chart/xAxis.tsx
- src/components/simulator/result/SimResultChartHeader.tsx
- src/components/simulator/result/SimResultSummaryGains.tsx
- src/components/simulator/utils.ts
- src/libs/d3/primitives/D3XAxis.tsx
- src/libs/queries/extApi/tokenPrice.ts
- src/libs/routing/routes/sim.tsx
- src/pages/simulator/index.tsx
> [Simulator] Bugs fixes

- e2e/utils/strategy/CreateStrategyDriver.ts
- e2e/utils/strategy/EditStrategyDriver.ts
- src/components/strategies/create/CreateStrategyOrders.tsx
- src/components/strategies/edit/EditStrategyBudgetContent.tsx
- src/components/strategies/edit/EditStrategyPricesContent.tsx
fix #1027 
Create / duplicate
Edit price 
Deposit
Withdraw
> Move sell above buy in forms

- src/components/simulator/input/d3Chart/D3ChartHandle.tsx
- src/components/simulator/input/d3Chart/D3ChartRect.tsx
- src/components/simulator/input/d3Chart/utils.ts
fix #1091 
Wait for the svg element to be rendered before running selection
> [Simulator] Fix undraggable rect & line

- e2e/utils/strategy/CreateStrategyDriver.ts
- e2e/utils/strategy/EditStrategyDriver.ts
- src/components/strategies/create/CreateStrategyOrders.tsx
- src/components/strategies/create/overlapping/CreateOverlappingRange.tsx
- src/components/strategies/create/overlapping/CreateOverlappingStrategy.tsx
- src/components/strategies/edit/EditStrategyPricesContent.tsx
- src/components/strategies/edit/overlapping/EditPriceOverlappingStrategy.tsx
- src/components/strategies/overlapping/OverlappingRange.tsx
- src/components/strategies/overlapping/OverlappingStrategyGraph.tsx
- src/components/strategies/useWarning.tsx
- src/components/strategies/utils.ts
- src/index.css
> Add approve warning in create/edit Strategies

- src/components/strategies/create/CreateStrategyOrders.tsx
> #1162 - text change

- src/config/sei/utils.ts
- Assetlist has changed and now USDC/USDC base address is not EVM but the pointer_contract.address is. Add check that pointer_contract exists and if so, check if it is EVM before adding
> Add check for pointer_contract address

- e2e/pages/trade.spec.ts
- e2e/utils/TokenApprovalDriver.ts
- e2e/utils/TradeDriver.ts
- e2e/utils/trade/types.ts
- src/components/common/approval/ApproveToken.tsx
- src/components/trade/tradeWidget/useTradeAction.ts
- src/libs/queries/chain/approval.ts
- Set get approval query invalidation after transaction success
- Improve e2e trade page test coverage
> Issue #1302 - Request approval again after successful trade

- src/libs/wagmi/wagmi.constants.ts
> Add mobile metamask rdns

- src/components/activity/ActivityProvider.tsx
> Fix pagination next page issues

- src/config/celo/common.ts
- src/libs/wagmi/chains.ts
fix #1413 
- Remove parenthesis and content within
- Limit the length of the symbol
> Parse network symbol from config

- public/_headers
fix #1418 
- Add headers file with Content-Security-Policy -> frame-ancestors set
> Add _headers file with Content-Security-Policy

- src/components/simulator/input/d3Chart/overlapping/D3ChartOverlapping.tsx
Reverts bancorprotocol/carbon-app#1409
> Revert "Use spread to calculate yPos in the D3ChartOverlapping"

- src/components/strategies/overview/strategyBlock/StrategyBlockManage.tsx
> Replace strategy manage button style from white to secondary

- src/components/strategies/portfolio/token/PortfolioToken.tsx
> Improve not found error for portfolio individual token search

- src/components/common/imager/Imager.tsx
- src/components/simulator/input/SimInputStrategyType.tsx
- src/components/strategies/common/TokenSelection.tsx
- src/components/trade/TradeNav.tsx
- src/components/trade/tradeWidget/NotEnoughLiquidity.tsx
- src/libs/routing/routes/index.ts
- src/libs/routing/routes/myStrategies.ts
- src/libs/routing/routes/trade.ts
> [Trade] Follow up

- src/components/activity/utils.ts
- src/libs/routing/routes/explorer.ts
- src/libs/routing/routes/myStrategies.ts
- src/libs/routing/routes/strategy.ts
Consolidate all activity-related validateSearch so that it parses the limit and offset correctly.
> Fix Individual strategy page activity pagination

- src/config/tac/common.ts
> display tac in chains menu

- src/config/tac/common.ts
> show trade count in TAC
