.eslintrc.json
package.json

Fixes two issues related to windows during installation : 
- `"endOfLine": "auto"`: fixes the `Delete 'CR'` warn on every end of line
- use escaped double quote in package.json because single quotes are interpreted as a folder name on windows

Windows issues

---

src/components/core/menu/mainMenu/MainMenuLeft.tsx
src/components/strategies/StrategyPageTabs.tsx

Small PR to get to know the code. 
Improve a11y for navigation : 
- use `nav` with `aria-label` to get implicit `navigation` role ([Documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav))
- use `aria-current="page"` on anchors for the main page & `aria-current="location"` for tabbed pages. ([Documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current))
- removed a div that had no impact on the UI

improve a11y on navigation

---

src/components/explorer/ExplorerSearch.tsx
src/components/explorer/utils.ts
src/components/strategies/overview/StrategyContent.tsx
src/components/strategies/overview/StrategyFilterSort.tsx
src/components/strategies/overview/utils.ts
src/services/localeStorage/index.ts
src/store/useStrategiesStore.ts

String literal are more readable than enum in :
- Codebase
- URL searchParams
- GTM events
As I had to send sort/filter to GTM I thought it would be better to start with this migration to string literals.

Replace strategy sort & filter enum

---

src/utils/fullOutcome.test.ts
src/utils/fullOutcome.ts

hotfix on geomean function

---

src/components/common/TokenInputField/Slippage.tsx
src/components/debug/DebugCreateStrategy.tsx
src/components/strategies/UserMarketPrice.tsx
src/components/strategies/create/BuySellBlock/InputLimit.tsx
src/components/strategies/create/BuySellBlock/InputRange.tsx
src/components/strategies/create/BuySellBlock/LimitRangeSection.tsx
src/components/strategies/create/overlapping/CreateOverlappingStrategy.tsx
src/components/strategies/edit/overlapping/DepositOverlappingStrategy.tsx
src/components/strategies/edit/overlapping/EditOverlappingStrategyBudget.tsx
src/components/strategies/edit/overlapping/EditPriceOverlappingStrategy.tsx
src/components/strategies/edit/overlapping/MarketWarning.tsx
src/components/strategies/edit/overlapping/WithdrawOverlappingStrategy.tsx
src/components/strategies/marketPriceIndication/useMarketIndication.ts
src/components/strategies/overlapping/OverlappingMarketPrice.tsx
src/components/strategies/overlapping/OverlappingStrategyGraph.tsx
src/components/strategies/useWarning.tsx
src/components/strategies/utils.ts
src/hooks/useMarketPrice.ts

- Check market price is unknown in useWarning
- Add warning text to LimitRangeSection to use in non-overlapping strategies

Show unknown market price warning

---

src/config/sei/common.ts
src/config/sei/utils.ts

The official assetlist has had all the tokens moved from 'pacific-1-evm' to 'pacific-1', with Cosmos and non-Cosmos addresses in the same list.
- Change tag from 'pacific-1-evm' to 'pacific-1'
- Check address retrieved is EVM address

Quick fix: Changes to assetlist

---

src/components/core/menu/mainMenu/MainMenuRightBurger/MenuItem.tsx
src/components/core/menu/mainMenu/MainMenuRightBurger/index.tsx
src/components/core/menu/mainMenu/MainMenuRightBurger/useBurgerMenuItems.tsx
src/config/ethereum/common.ts
src/config/types.ts
src/libs/modals/modals/ModalBurgerMenu.tsx
src/libs/routing/externalLinks.ts

- Add optional carbonAnalytics config param and add it to the Ethereum config only
- Remove "Analytics" from menu if url is undefined in config
- Remove "Dune Dashboard" from menu if url is undefined in config
- Remove "Interactive Sim" from menu if url is undefined in config
- Remove "Simulator Repo" from menu if url is undefined in config
fix #1308

Issue #1308 - Remove analytics link for Sei

---

src/init-sentry.ts

Sentry.captureConsoleIntegration() has the following options for what console output to send to Sentry:
['log', 'info', 'warn', 'error', 'debug', 'assert']
This PR changes the init-sentry to only send console output for 'error'

Fix init-sentry to only send console errors to Sentry

---

e2e/utils/modal.ts
src/components/activity/ActivityProvider.tsx
src/components/activity/ActivitySection.tsx
src/pages/strategies/activity/index.tsx

fix #1395
- Pair filter is now working
- Empty state leave the filters
Test case: "Pair filter"
- go to explorer with wallet address: 0x5f7a009664b771e889751f4fd721adc439033ecd
- go to activity tab
- select pair DAI/USDC
- filter works
- add USDC/BBS
-> It only display USDC/BBS, while it should display both. This is because backend response is not correct.
Test case "Empty State"
- go to explorer with wallet address: 0x5f7a009664b771e889751f4fd721adc439033ecd*
- filter by date from 1st of July to 2nd of July
- Display empty state, but filter are accessible

fix filter & empty state

---

src/config/sei/utils.ts
src/libs/tokens/tokenHelperFn.ts

fix #1415
Issue was observed in Safari 15.6 and Mobile Safari 15.5.
Versions from Safari > 11.4 and Mobile Safari > 11.3 support [fetch signal](https://caniuse.com/?search=fetch%20signal)
Versions from Safari 16.0 and Mobile Safari > 16.0 support [AbortSignal.timeout().](https://caniuse.com/?search=abortsignal%20timeout)
To support users using Safari 15.6 and Mobile Safari 15.5, the timeout logic for fetching token lists is changed to avoid using AbortSignal.timeout().

[SENTRY] Change the way fetch signal is timed out on token list fetches

---

src/components/common/selectToken/index.tsx
src/components/simulator/input/BuySellBlockNew/Header.tsx
src/components/simulator/input/SimInputStrategyType.tsx
src/components/simulator/input/SimInputTokenSelection.tsx
src/components/strategies/StrategyPageTabs.tsx
src/components/strategies/common/OrderHeader.tsx
src/components/strategies/create/CreateLayout.tsx
src/components/strategies/create/CreateStrategyOption.tsx
src/components/strategies/create/CreateStrategyTokenSelection.tsx
src/components/strategies/edit/EditPriceNav.tsx
src/components/strategies/edit/EditStrategyLayout.tsx
src/components/strategies/overlapping/OverlappingBudget.module.css
src/components/strategies/overview/strategyBlock/StrategyBlockCreate.tsx

fix #1189 
- Token selection
- New strategy CTA
- Strategy page tabs
- Strategy Type
- Order type
- Open/Close chart
- Simulator strategy type and token selection
- Overlapping Anchor
- Overlapping edit budget Withdraw/Deposit

Add mouse hover effects

---

src/components/simulator/input/d3Chart/overlapping/D3ChartOverlapping.tsx

fix #1345
Updating spread was not having an effect in D3ChartOverlapping as the spread was not being used when calculating the yPos for the buyMax and sellMin. Spread is now used with calcPrices to get buyMax and sellMin.

Use spread to calculate yPos in the D3ChartOverlapping

---

src/components/common/approval/ApproveToken.tsx

fix #1346 
- Approval message was showing a JSON.stringify of the error. 
- Since it comes from a tanstack-react query, the error.message can be displayed instead of the entire error object.
- Adjusted the layout of the approval modal so that the height expands as needed to accommodate the error and the error occupies a minimum width.

Improve display on approval error message

---

src/components/common/BackButton.tsx
src/components/strategies/create/CreateLayout.tsx
src/components/strategies/edit/EditStrategyLayout.tsx
src/pages/simulator/result/index.tsx
src/pages/strategies/create/token.tsx
src/pages/strategy/index.tsx

Fix #1186
Make back button styling consistent.
Current: 'bg-background-800' for most buttons, and 'bg-background-900 hover:bg-background-800' in the strategy page
Change to: 'bg-background-900 hover:bg-background-800' as the strategy page is the most recent page made.
Make "Simulate Strategy" in the Simulator Results page not clickable.

Fix inconsistent back button styling

---

src/components/trade/tradeWidget/useBuySell.ts
src/components/trade/tradeWidget/useTradeAction.ts
src/libs/modals/modals/ModalTradeRouting/ModalTradeRouting.tsx
src/libs/modals/modals/ModalTradeRouting/useModalTradeRouting.ts
src/libs/queries/sdk/trade.ts

fix #675
- Move logic to mutation
- Use isAwaiting = mutation.isPending instead of an awaiting state
- Update everywhere that uses the trade action hook

Move trade transaction to a mutation

---

src/components/simulator/result/SimResultChartControls.tsx
src/components/simulator/result/SimulatorProvider.tsx

- Reply function only calls handleAnimationStep if it is not already running, in which cases the handleAnimationStep look is already happening
- Use replay function in SimResultChartControls
fix #1217

[Simulator] Fix replay increasing speed

---

src/components/simulator/input/d3Chart/overlapping/D3ChartOverlapping.tsx
src/components/simulator/input/d3Chart/overlapping/useD3OverlappingChart.test.ts
src/components/simulator/input/d3Chart/overlapping/useD3OverlappingChart.ts

- Move yPos and calcPrices to a separate hook
- Use calcPrices to get buyMax and sellMin
- Add tests for the hook
fix #1345

Fix overlapping chart not updating with spread changes

---

src/components/core/menu/mainMenu/MainMenuRightChainSelector.tsx
src/config/index.ts
src/libs/wagmi/connectors.ts
src/libs/wagmi/useWagmiUser.ts

By default, safe wallet opens the CarbonDeFi app on https://app.carbondefi.xyz:
Detect redirection must be made:
- User is in an iFrame - meaning CarbonDeFi is open on a Safe Wallet as this is the only external address frame-ancestor allowed in the CSP
- Current chain Id is different than safe wallet chain Id
fix #1398

Redirect app to correct app URL in a Safe Wallet

---

.github/workflows/update_browserslist.yaml
yarn.lock

Bumps caniuse-lite to 1.0.30001679.
Update output: 
yarn run v1.22.22
$ npx update-browserslist-db@latest
Latest version:     1.0.30001679
Installed version:  1.0.30001677
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
Cleaning package.json dependencies from caniuse-lite
$ yarn remove -W caniuse-lite
caniuse-lite has been successfully updated
No target browser changes
Done in 17.29s.

Bump browserslist DB to 1.0.30001679

---

package.json
src/libs/wagmi/connectors.ts
yarn.lock

Wagmi now checks if injected wallets already exist to avoid duplicating them.
- Update wagmi to 2.12.32
- Remove logic to check already injected wallets
- Remove unnecessary mipd package

Update wagmi to 2.12.32

---

yarn.lock

Bumps caniuse-lite to 1.0.30001684.
Update output: 
yarn run v1.22.22
$ npx update-browserslist-db@latest
Latest version:     1.0.30001684
Installed version:  1.0.30001679
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
Cleaning package.json dependencies from caniuse-lite
$ yarn remove -W caniuse-lite
caniuse-lite has been successfully updated
No target browser changes
Done in 16.96s.

Bump browserslist DB to 1.0.30001684
